trigger:
  branches:
    include:
      - main
      - master
      - development
      - develop
      - release/*

pr:
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: self
      type: git
      name: SiddiqSoft/restcl

parameters:
  - name: RunWindows
    type: boolean
    default: true
  - name: RunLinux
    type: boolean
    default: true
  - name: Architecture
    type: string
    default: arm64
    values:
      - x64
      - arm64
  - name: LinuxCompiler
    type: string
    default: GCC
    values:
      - GCC
      - Clang

stages:
  - stage: BuildWindows
    displayName: Windows ${{ parameters.Architecture }}
    condition: eq(${{ parameters.RunWindows }}, true)
    jobs:
      - template: .ci/azure-pipelines-windows-template.yml
        parameters:
          displayName: Windows
          architecture: ${{ parameters.Architecture }}
          matrixConfigs:
            Windows_Release:
              BuildType: Release
              cmake.preset: Windows-${{ parameters.Architecture }}-$(BuildType)
            Windows_Debug:
              BuildType: Debug
              cmake.preset: Windows-${{ parameters.Architecture }}-$(BuildType)
          runTests: false
          publishNuGet: false
          publishGitHub: false

  - stage: BuildLinux
    displayName: Linux ${{ parameters.LinuxCompiler }}
    condition: eq(${{ parameters.RunLinux }}, true)
    jobs:
      - template: .ci/azure-pipelines-linux-template.yml
        parameters:
          displayName: Linux ${{ parameters.LinuxCompiler }}
          linuxCompiler: ${{ parameters.LinuxCompiler }}
          matrixConfigs:
            Linux_Release:
              BuildType: Release
              cmake.preset: Linux-${{ parameters.LinuxCompiler }}-$(BuildType)
            Linux_Debug:
              BuildType: Debug
              cmake.preset: Linux-${{ parameters.LinuxCompiler }}-$(BuildType)
          runTests: false

  - stage: TestWindows
    displayName: Test Windows ${{ parameters.Architecture }}
    dependsOn:
      - BuildWindows
      - BuildLinux # we're not dependent on the build but for avoiding parallelism limit on Azure!
    jobs:
      - template: .ci/azure-pipelines-test-template.yml
        parameters:
          architecture: ${{ parameters.Architecture }}
          matrixConfigs:
            Windows_Release:
              BuildType: Release
              cmake.preset: Windows-${{ parameters.Architecture }}-$(BuildType)
            Windows_Debug:
              BuildType: Debug
              cmake.preset: Windows-${{ parameters.Architecture }}-$(BuildType)

  - stage: TestLinux
    displayName: Test Linux ${{ parameters.LinuxCompiler }}
    dependsOn:
      - BuildLinux
      - TestWindows # we're not dependent on the build but for avoiding parallelism limit on Azure!
    jobs:
      - template: .ci/azure-pipelines-test-template.yml
        parameters:
          architecture: ${{ parameters.Architecture }}
          matrixConfigs:
            Linux_Release:
              BuildType: Release
              cmake.preset: Linux-${{ parameters.LinuxCompiler }}-$(BuildType)
            Linux_Debug:
              BuildType: Debug
              cmake.preset: Linux-${{ parameters.LinuxCompiler }}-$(BuildType)

  - stage: NuGetPublish
    displayName: NuGet Publish
    dependsOn:
      - TestWindows
      - TestLinux
    condition: succeeded()
    jobs:
      - template: .ci/azure-pipelines-nuget-publish-template.yml

  - stage: GitHubRelease
    displayName: GitHub Release
    dependsOn:
      - TestLinux
      - TestWindows
      - NuGetPublish
    condition: succeeded()
    jobs:
      - template: .ci/azure-pipelines-github-release-template.yml
