parameters:
  - name: displayName
    type: string
  - name: architecture
    type: string
  - name: matrixConfigs
    type: object

jobs:
  - job: ${{ parameters.architecture }}
    displayName: ${{ parameters.displayName }}
    workspace:
      clean: all
    pool:
      name: Default
      demands:
        - Agent.OS -equals Windows_NT
        - Agent.OSArchitecture -equals ${{ parameters.architecture }}
    strategy:
      matrix: ${{ parameters.matrixConfigs }}
    steps:
      - checkout: self
        name: step1

      - task: CmdLine@2
        displayName: "Install Ninja on Windows"
        inputs:
          script: |
            winget install ninja-build.ninja
            ninja --version
        continueOnError: true
          
      - task: BatchScript@1
        displayName: "Detect the paths of Visual Studio and MSBuild.."
        inputs:
          filename: pipeline_detect_vs_path.bat
          modifyEnvironment: true
      
      - task: BatchScript@1
        displayName: "Invoke the vcvarsall.bat to set up the environment for Visual Studio.."
        inputs:
          filename: pipeline_call_vs_path.bat
          modifyEnvironment: true
      
      - task: BatchScript@1
        displayName: "Install paths.. %VCVARS_PATH%"
        inputs:
          filename: '%VCVARS_PATH%'
          modifyEnvironment: true
      
      - task: CmdLine@2
        displayName: "Review all environment variables."
        inputs:
          script: |
            set
        continueOnError: true
      
      - task: gitversion-setup@4
        displayName: "Install GitVersion.."
        inputs:
          versionSpec: "6.x"
          preferLatestVersion: true

      - task: gitversion-execute@4
        displayName: "Determine Version.."
        name: version_step
        inputs:
          useConfigFile: true
          configFilePath: "GitVersion.yml"

      - script: |
          REM Detect Visual Studio version and edition on ARM64 or x64
          set VS_VERSION=
          set VS_PATH=
          
          REM Check for VS 2026 (Enterprise, Professional, Community)
          for %%E in (Enterprise Professional Community) do (
            if exist "C:\Program Files\Microsoft Visual Studio\2026\%%E\VC\Auxiliary\Build\vcvarsall.bat" (
              set VS_VERSION=2026
              set VS_PATH=C:\Program Files\Microsoft Visual Studio\2026\%%E
              goto vs_found
            )
          )
          
          REM Check for VS 2022 (Enterprise, Professional, Community)
          for %%E in (Enterprise Professional Community) do (
            if exist "C:\Program Files\Microsoft Visual Studio\2022\%%E\VC\Auxiliary\Build\vcvarsall.bat" (
              set VS_VERSION=2022
              set VS_PATH=C:\Program Files\Microsoft Visual Studio\2022\%%E
              goto vs_found
            )
          )
          
          :vs_found
          if not defined VS_VERSION (
            echo "Visual Studio 2022 or 2026 not found on agent"
            exit /b 1
          )
          
          echo Visual Studio %VS_VERSION% found at %VS_PATH%
          echo ##vso[task.setvariable variable=VS_VERSION]%VS_VERSION%
          echo ##vso[task.setvariable variable=VS_PATH]%VS_PATH%
        displayName: 'Detect Visual Studio Version'

      - task: CMake@1
        displayName: "CMake Configure $(cmake.preset)"
        inputs:
          cmakeArgs: "--preset $(cmake.preset) -DCI_BUILDID=$(GITVERSION_MAJORMINORPATCH) -DCPM_SOURCE_CACHE=$(Agent.HomeDirectory)/.cpmcache"
          workingDirectory: "$(System.DefaultWorkingDirectory)"

      - task: CMake@1
        displayName: "CMake Build $(cmake.preset)"
        inputs:
          cmakeArgs: "--build --preset $(cmake.preset) -DCI_BUILDID=$(GITVERSION_MAJORMINORPATCH)  -DCPM_SOURCE_CACHE=$(Agent.HomeDirectory)/.cpmcache"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
        condition: succeeded()

      - task: CMake@1
        displayName: "CMake Tests $(cmake.preset)"
        inputs:
          cmakeArgs: "-E chdir $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests ctest $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests --output-junit $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests/results/$(cmake.preset)_test_detail.xml --output-on-failure"
        continueOnError: true
        condition: succeeded()

      - task: PublishTestResults@2
        displayName: "Publish $(BuildType) Test Results $(cmake.preset)_test_detail.xml"
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "$(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests/results/$(cmake.preset)_test_detail.xml"
          mergeTestResults: false
          buildConfiguration: "$(BuildType)"
        continueOnError: true
        condition: succeeded()

      - task: NuGetToolInstaller@1
        displayName: "Install Nuget on Windows"
        inputs:
          versionSpec: ">=6.0.0-0"
          checkLatest: true
        condition: and(succeeded(), startsWith(variables['Agent.OS'], 'Windows'))

      - task: NuGetCommand@2
        displayName: "NuGet pack v$(GITVERSION_MAJORMINORPATCH)"
        inputs:
          command: "pack"
          packagesToPack: "pack/*.nuspec"
          versioningScheme: "off"
          buildProperties: "VERSION=$(GITVERSION_MAJORMINORPATCH)"
        condition: and(succeeded(), startsWith(variables['Agent.OS'], 'Windows'))

      - task: NuGetCommand@2
        displayName: "NuGet push (Windows only)"
        inputs:
          command: "push"
          packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;build/*.nupkg"
          nuGetFeedType: "external"
          publishFeedCredentials: "sqs-nuget"
        condition: and(succeeded(), eq(variables['BuildType'], 'Release'), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')), startsWith(variables['Agent.OS'], 'Windows'))

      - task: GitHubRelease@1
        displayName: "Release to GitHub"
        inputs:
          gitHubConnection: "github-packages-sqs"
          repositoryName: "$(Build.Repository.Name)"
          action: "create"
          target: "$(Build.SourceVersion)"
          tagSource: "userSpecifiedTag"
          tag: "$(GITVERSION_MAJORMINORPATCH)"
          title: "v$(GITVERSION_MAJORMINORPATCH)"
          releaseNotesSource: "inline"
          releaseNotesInline: "Documentation https://github.com/$(Build.Repository.Name)"
          isPreRelease: true
          changeLogCompareToRelease: "lastFullRelease"
          changeLogType: "commitBased"
          addChangeLog: false
          assetUploadMode: "replace"
        condition: and(succeeded(), eq(variables['BuildType'], 'Release'), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')), startsWith(variables['Agent.OS'], 'Windows'))
