trigger:
  branches:
    include:
      - main
      - master
      - development
      - develop
      - release/*

pr:
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: self
      type: git
      #name: ${{ parameters.repoToCheckout }}

parameters:
  - name: RunWindows
    type: boolean
    default: true
  - name: RunLinux
    type: boolean
    default: true
  - name: RunLinuxClangOnly
    displayName: "RunLinuxClangOnly - Check to only run the Linux Clang builds and skip the Linux GCC builds"
    type: boolean
    default: true
  - name: BuildX64
    displayName: "BuildX64 - Check to enable the x64 builds"
    type: boolean
    default: false
  - name: BuildDebug
    displayName: "BuildDebug - Check to enable the Debug builds"
    type: boolean
    default: false
  - name: PublishNuGet
    displayName: "PublishNuGet - Defaults to false; auto set to true when on main/master"
    type: boolean
    default: false
  - name: PublishGitHub
    displayName: "PublishGitHub - Defaults to false; auto set to true when on main/master"
    type: boolean
    default: false
  - name: RunTests
    displayName: "RunTests - Check to run tests after building"
    type: boolean
    default: true

variables:
  # Set the publish if we're building on main/master
  ${{ if and(eq(parameters.PublishNuGet, false), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))) }}:
    PublishNuGet: true
    PublishGitHub: true
  ${{ else }}:
    PublishNuGet: ${{ parameters.PublishNuGet }}
    PublishGitHub: ${{ parameters.PublishGitHub }}
  ThisAgentOS: $(Agent.OS)
  ThisAgentArch: $(Agent.OSArchitecture)
  THISBUILDVERSION: "0.0.0"
  THATBUILDVERSION: "9.9.8"

stages:
  - stage: StgBldWindows
    displayName: Windows
    dependsOn: []
    condition: eq(${{ parameters.RunWindows }}, true)
    jobs:
        # This option is available only for x64 builds for Windows.
      - template: .ci/azure-pipelines-windows-template.yml
        parameters:
          displayName: Windows x64
          architecture: x64
          matrixConfigs:
            Windows_x64_Release:
              BuildType: Release
              BuildArchitecture: x64
              cmake.preset: Windows-$(BuildArchitecture)-$(BuildType)
              # This option is available for debug
            ${{ if eq(parameters.BuildDebug, true) }}:
              Windows_x64_Debug:
                BuildType: Debug
                BuildArchitecture: x64
                cmake.preset: Windows-$(BuildArchitecture)-$(BuildType)
          runTests: ${{ parameters.RunTests }}
          publishNuGet: ${{ parameters.PublishNuGet }}
          BuildX64: ${{ parameters.BuildX64 }}
          BuildDebug: ${{ parameters.BuildDebug }}
      - template: .ci/azure-pipelines-windows-template.yml
        parameters:
          displayName: Windows arm64
          architecture: arm64
          matrixConfigs:
            Windows_arm64_Release:
              BuildType: Release
              BuildArchitecture: arm64
              cmake.preset: Windows-$(BuildArchitecture)-$(BuildType)
              # This option is available for debug
            ${{ if eq(parameters.BuildDebug, true) }}:
              Windows_arm64_Debug:
                BuildType: Debug
                BuildArchitecture: arm64
                cmake.preset: Windows-$(BuildArchitecture)-$(BuildType)
          runTests: ${{ parameters.RunTests }}
          publishNuGet: ${{ parameters.PublishNuGet }}
          BuildX64: ${{ parameters.BuildX64 }}
          BuildDebug: ${{ parameters.BuildDebug }}

  - stage: StgBldLinux
    displayName: Linux
    dependsOn: []
    condition: eq(${{ parameters.RunLinux }}, true)
    jobs:
      - template: .ci/azure-pipelines-linux-template.yml
        parameters:
          displayName: Linux Clang
          matrixConfigs:
            Linux_Clang_Release:
              BuildType: Release
              LinuxCompiler: Clang
              cmake.preset: Linux-$(LinuxCompiler)-$(BuildType)
            ${{ if eq(parameters.BuildDebug, true) }}:
              Linux_Clang_Debug:
                BuildType: Debug
                LinuxCompiler: Clang
                cmake.preset: Linux-$(LinuxCompiler)-$(BuildType)
          runTests: ${{ parameters.RunTests }}
        # this job is "activated" when RunLinuxClangOnly is false.
      - ${{ if eq(parameters.RunLinuxClangOnly, false) }}:
        - template: .ci/azure-pipelines-linux-template.yml
          parameters:
            displayName: Linux GCC
            matrixConfigs:
              Linux_GCC_Release:
                BuildType: Release
                LinuxCompiler: GCC
                cmake.preset: Linux-$(LinuxCompiler)-$(BuildType)
              ${{ if eq(parameters.BuildDebug, true) }}:
                Linux_GCC_Debug:
                  BuildType: Debug
                  LinuxCompiler: GCC
                  cmake.preset: Linux-$(LinuxCompiler)-$(BuildType)
            runTests: ${{ parameters.RunTests }}

  - stage: Publication
    displayName: Nuget Publication and GitHub Release
    dependsOn:
      - StgBldWindows
      - StgBldLinux
    condition: and(succeeded(), eq(variables['PublishGitHub'], true))
    jobs:
      - template: .ci/azure-pipelines-github-release-template.yml
        parameters:
          displayName: Nuget and GitHub Release 
          PublishNuGet: ${{ variables.PublishNuGet }}
          PublishGitHub: ${{ variables.PublishGitHub }}
          ExtraParam: $[ stageDependencies.StgBldWindows.JobWindowsBuild_arm64.outputs['SETVER.VTAG'] ]
