parameters:
  - name: displayName
    type: string
  - name: PublishNuGet
    type: boolean
    default: true

jobs:
  - job: NugetRelease
    displayName: Nuget Release
    pool:
      name: Default
      #demands:
      #  - Agent.OS -equals Windows_NT
    
    variables:
      TagVersion: $(Build.BuildNumber)

    steps:
      - checkout: none
        
      - task: CmdLine@2
        displayName: "Echo variables for debugging"
        inputs:
          script: |
            echo "TagVersion:  $(TagVersion)"
            echo "BuildNumber:  $(Build.BuildNumber)"
            echo "----------------------------------------------------------------"
            set 
      
      - task: DownloadBuildArtifacts@0
        displayName: "Download NuGet packages"
        inputs:
          downloadType: "single"
          artifactName: "nuget-packages"
          downloadPath: "$(Build.ArtifactStagingDirectory)"
        condition: succeeded()

      - task: NuGetCommand@2
        displayName: "NuGet push v$(TagVersion)"
        inputs:
          command: "push"
          packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg"
          nuGetFeedType: "external"
          publishFeedCredentials: "sqs-nuget"
        condition: and(succeeded(), eq(variables['PublishNuGet'], true))
