parameters:
  - name: displayName
    type: string
  - name: linuxCompiler
    type: string
  - name: matrixConfigs
    type: object
  - name: runTests
    type: boolean
    default: true

jobs:
  - job: Linux
    displayName: ${{ parameters.displayName }}
    workspace:
      clean: all
    pool:
      name: Default
      demands:
        - Agent.OS -equals Linux
    strategy:
      matrix: ${{ parameters.matrixConfigs }}
    steps:
      - checkout: self
        name: step1

      - task: gitversion-setup@4
        displayName: "Install GitVersion"
        inputs:
          versionSpec: "6.x"
          preferLatestVersion: true

      - task: gitversion-execute@4
        displayName: "Determine Version"
        name: version_step
        inputs:
          useConfigFile: true
          configFilePath: "GitVersion.yml"

      - task: CMake@1
        displayName: "CMake Configure $(cmake.preset)"
        inputs:
          cmakeArgs: "--preset $(cmake.preset) -DCI_BUILDID=$(GITVERSION_MAJORMINORPATCH) -DCPM_SOURCE_CACHE=$(Agent.HomeDirectory)/.cpmcache"
          workingDirectory: "$(System.DefaultWorkingDirectory)"

      - task: CMake@1
        displayName: "CMake Build $(cmake.preset)"
        inputs:
          cmakeArgs: "--build --preset $(cmake.preset) -DCI_BUILDID=$(GITVERSION_MAJORMINORPATCH) -DCPM_SOURCE_CACHE=$(Agent.HomeDirectory)/.cpmcache"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
        condition: succeeded()

        # Running tests requires the files to be on the same machine and working folder.
        # If we try to separate these tests into different stages they will run on different machines and fail to find the files.
      - task: CMake@1
        displayName: "CMake Tests $(cmake.preset)"
        inputs:
          cmakeArgs: "-E chdir $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests ctest --output-junit $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests/results/$(cmake.preset)_test_detail.xml --output-on-failure"
        continueOnError: true
        condition: and(succeeded(), eq(${{ parameters.runTests }}, true))

        # Here we publish the results for Release build and for Debug only if those fail.
      - task: PublishTestResults@2
        displayName: "Publish Test Results $(cmake.preset)_test_detail.xml"
        inputs:
          testResultsFormat: "JUnit"
          testRunTitle: "Tests $(cmake.preset)"
          testResultsFiles: "$(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests/results/$(cmake.preset)_test_detail.xml"
          mergeTestResults: false
          buildConfiguration: "$(BuildType)"
        continueOnError: true
        condition: and(succeeded(), eq(${{ parameters.runTests }}, true), or(eq(variables['BuildType'], 'Release'), failed()))
