parameters:
  - name: displayName
    type: string
  - name: PublishNuGet
    type: boolean
    default: true
  - name: PublishGitHub
    type: boolean
    default: true
  - name: ExtraParam0
    type: string
    default: "0.0.0"
  - name: ExtraParam1
    type: string
    default: "0.0.1"

  - job: NugetRelease
    variables:
      xtmp0: $[stageDependencies.StgBldLinux.JobLinuxBuild.outputs['SETVER.VTAG']]
      xtmp0a: $[stageDependencies.StgBldLinux.JobLinuxBuild.outputs['SETVER_VTAG']]
      xtmp1: $[stageDependencies.StgBldWindows.JobWindowsBuild_arm64.outputs['SETVER0.VTAG0']]
      xtmp1a: $[stageDependencies.StgBldWindows.JobWindowsBuild_arm64.outputs['SETVER0_VTAG0']]
    displayName: Nuget Release
    pool:
      name: Default
      #demands:
      #  - Agent.OS -equals Windows_NT

    steps:
      - checkout: none
      #- task: DownloadBuildArtifacts@0
      #  displayName: "Download release assets"
      #  inputs:
      #    downloadType: "single"
      #    artifactName: "release-assets"
      #    downloadPath: "$(Build.ArtifactStagingDirectory)"
        
      - task: CmdLine@2
        displayName: "Echo variables for debugging"
        inputs:
          script: |
            echo "PublishNuGet: $(PublishNuGet)"
            echo "extraparam0: $(ExtraParam0). ${{ parameters.ExtraParam0 }}"
            echo "extraparam1: $(ExtraParam1)   ${{ parameters.ExtraParam1 }}"
            echo "xtmp0: $(xtmp0)"
            echo "xtmp0a: $(xtmp0a)"
            echo "xtmp1: $(xtmp1)"
            echo "xtmp1a: $(xtmp1a)"
            echo "----------------------------------------------------------------"
            set 
      
      - task: DownloadBuildArtifacts@0
        displayName: "Download NuGet packages"
        inputs:
          downloadType: "single"
          artifactName: "nuget-packages"
          downloadPath: "$(Build.ArtifactStagingDirectory)"
        condition: succeeded()

      - task: NuGetCommand@2
        displayName: "NuGet push v$(TagVersion)"
        inputs:
          command: "push"
          packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg"
          nuGetFeedType: "external"
          publishFeedCredentials: "sqs-nuget"
        condition: and(succeeded(), eq(variables['PublishNuGet'], true))
