parameters:
  - name: displayName
    type: string
  - name: PublishNuGet
    type: boolean
    default: true
  - name: PublishGitHub
    type: boolean
    default: true
  - name: ExtraParam0
    type: string
    default: "0.0.0"
  - name: ExtraParam1
    type: string
    default: "0.0.1"

jobs:
  - job: GitHubRelease
    displayName: GitHub Release
    pool:
      name: Default
      demands:
        - Agent.OS -equals Windows_NT

    steps:
      - checkout: none
      #- task: DownloadBuildArtifacts@0
      #  displayName: "Download release assets"
      #  inputs:
      #    downloadType: "single"
      #    artifactName: "release-assets"
      #    downloadPath: "$(Build.ArtifactStagingDirectory)"
        
      - task: CmdLine@2
        displayName: "Echo variables for debugging"
        inputs:
          script: |
            echo "PublishNuGet: $(PublishNuGet)"
            echo "extraparam0: ${{ parameters.ExtraParam0 }}"
            echo "extraparam0: $(ExtraParam0)"
            echo "extraparam1: ${{ parameters.ExtraParam1 }}"
            echo "extraparam1: $(ExtraParam1)"
            echo "----------------------------------------------------------------"
            set 
      
      - task: DownloadBuildArtifacts@0
        displayName: "Download NuGet packages"
        inputs:
          downloadType: "single"
          artifactName: "nuget-packages"
          downloadPath: "$(Build.ArtifactStagingDirectory)"
        condition: succeeded()

      - task: NuGetCommand@2
        displayName: "NuGet push v$(TagVersion)"
        inputs:
          command: "push"
          packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg"
          nuGetFeedType: "external"
          publishFeedCredentials: "sqs-nuget"
        condition: and(succeeded(), eq(variables['PublishNuGet'], true))

      - task: GitHubRelease@1
        displayName: "Release to GitHub v$(TagVersion)"
        inputs:
          gitHubConnection: "github-packages-sqs"
          repositoryName: "$(Build.Repository.Name)"
          action: "create"
          target: "$(Build.SourceVersion)"
          tagSource: "userSpecifiedTag"
          tag: "$(TagVersion)"
          title: "v$(TagVersion)"
          releaseNotesSource: "inline"
          releaseNotesInline: "Documentation https://github.com/$(Build.Repository.Name)"
          isPreRelease: true
          changeLogCompareToRelease: "lastFullRelease"
          changeLogType: "commitBased"
          addChangeLog: false
          assetUploadMode: "replace"
          assets: "$(Build.ArtifactStagingDirectory)/**/*"
        condition: and(succeeded(), eq(variables['PublishGitHub'], true))
