# Requirements:
# The self-hosted build agents must have CMake and Ninja installed and available in PATH for this pipeline to work.
parameters:
  - name: displayName
    type: string
  - name: architecture
    type: string
  - name: matrixConfigs
    type: object
  - name: runTests
    type: boolean
    default: true
  - name: publishNuGet
    type: boolean
    default: false
  - name: BuildX64
    type: boolean
    default: false
  - name: BuildDebug
    type: boolean
    default: false

jobs:
  - job: ${{ parameters.architecture }}
    # build x64 only if the BuildX64 parameter is true and the architecture parameter is x64
    # otherwise build all architectures that are in the matrixConfigs
    #condition: or(not(eq(${{ parameters.BuildX64 }}, true)), and(eq(${ parameters.BuildX64 }}, true), eq(${{ parameters.architecture }}, "x64")))
    condition: or( not(eq("${{ parameters.architecture }}", "x64")), and(eq(${{ parameters.BuildX64 }}, true), eq("${{ parameters.architecture }}", "x64")) )
    displayName: ${{ parameters.displayName }}
    workspace:
      clean: all
    pool:
      name: Default
      demands:
        - Agent.OS -equals Windows_NT
        - Agent.OSArchitecture -equals ${{ parameters.architecture }}
    strategy:
      matrix: ${{ parameters.matrixConfigs }}
    steps:
      - checkout: self
        name: step1

      - task: BatchScript@1
        displayName: "Detect Visual Studio paths"
        inputs:
          filename: "$(System.DefaultWorkingDirectory)/.ci/pipeline_detect_vs_path.bat"
          modifyEnvironment: true

      - task: BatchScript@1
        displayName: "Setup MSVC environment"
        inputs:
          filename: '$(VCVARS_PATH)'
          arguments: '$(AGENT_OSARCHITECTURE)'
          modifyEnvironment: true

      - task: gitversion-setup@4
        displayName: "Install GitVersion"
        inputs:
          versionSpec: "6.x"
          preferLatestVersion: true

      - task: gitversion-execute@4
        displayName: "Determine Version"
        name: version_step
        inputs:
          useConfigFile: true
          configFilePath: "GitVersion.yml"

      - task: CMake@1
        displayName: "CMake Configure $(cmake.preset)"
        inputs:
          cmakeArgs: "--preset $(cmake.preset) -DCI_BUILDID=$(GITVERSION_MAJORMINORPATCH) -DCPM_SOURCE_CACHE=$(Agent.HomeDirectory)/.cpmcache"
          workingDirectory: "$(System.DefaultWorkingDirectory)"

      - task: CMake@1
        displayName: "CMake Build $(cmake.preset)"
        inputs:
          cmakeArgs: "--build --preset $(cmake.preset) -DCI_BUILDID=$(GITVERSION_MAJORMINORPATCH) -DCPM_SOURCE_CACHE=$(Agent.HomeDirectory)/.cpmcache"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
        condition: succeeded()

      #- task: PublishBuildArtifacts@1
      #  displayName: "Publish Windows build artifact $(cmake.preset)"
      #  inputs:
      #    PathtoPublish: "$(System.DefaultWorkingDirectory)/build/$(cmake.preset)"
      #    ArtifactName: "build-$(cmake.preset)"
      #    publishLocation: "Container"
      #  condition: succeeded()

      - task: CMake@1
        displayName: "CMake Tests $(cmake.preset)"
        inputs:
          cmakeArgs: "-E chdir $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests ctest --output-junit $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests/results/$(cmake.preset)_test_detail.xml --output-on-failure"
        continueOnError: true
        condition: and(succeeded(), eq(${{ parameters.runTests }}, true))

        # Here we publish the results for Release build and for Debug only if those fail.
      - task: PublishTestResults@2
        displayName: "Publish Test Results $(cmake.preset)_test_detail.xml"
        inputs:
          testResultsFormat: "JUnit"
          testRunTitle: "Tests $(cmake.preset)"
          testResultsFiles: "$(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests/results/$(cmake.preset)_test_detail.xml"
          mergeTestResults: false
          buildConfiguration: "$(BuildType)"
        continueOnError: true
        condition: and(succeeded(), eq(${{ parameters.runTests }}, true), or(eq(variables['BuildType'], 'Release'), failed()))

      - task: NuGetToolInstaller@1
        displayName: "Install NuGet"
        inputs:
          versionSpec: ">=6.0.0-0"
          checkLatest: true
        condition: succeeded()

      - task: NuGetCommand@2
        displayName: "NuGet pack v$(GITVERSION_MAJORMINORPATCH)"
        inputs:
          command: "pack"
          packagesToPack: "pack/*.nuspec"
          versioningScheme: "off"
          buildProperties: "VERSION=$(GITVERSION_MAJORMINORPATCH)"
        condition: succeeded()

      - task: PublishBuildArtifacts@1
        displayName: "Publish NuGet Artifacts"
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "nuget-packages"
          publishLocation: "Container"
        condition: succeeded()

      #- task: NuGetCommand@2
      #  displayName: "NuGet push"
      #  inputs:
      #    command: "push"
      #    packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg"
      #    nuGetFeedType: "external"
      #    publishFeedCredentials: "sqs-nuget"
      #  condition: and(succeeded(), eq(${{ parameters.publishNuGet }}, true), eq(variables['BuildType'], 'Release'), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
