parameters:
  - name: displayName
    type: string
  - name: linuxCompiler
    type: string
  - name: matrixConfigs
    type: object
  - name: runTests
    type: boolean
    default: true

jobs:
  - job: Linux
    displayName: ${{ parameters.displayName }}
    workspace:
      clean: all
    pool:
      name: Default
      demands:
        - Agent.OS -equals Linux
    strategy:
      matrix: ${{ parameters.matrixConfigs }}
    steps:
      - checkout: self
        name: step1

      - task: gitversion-setup@4
        displayName: "Install GitVersion"
        inputs:
          versionSpec: "6.x"
          preferLatestVersion: true

      - task: gitversion-execute@4
        displayName: "Determine Version"
        name: version_step
        inputs:
          useConfigFile: true
          configFilePath: "GitVersion.yml"

      - task: CMake@1
        displayName: "CMake Configure $(cmake.preset)"
        inputs:
          cmakeArgs: "--preset $(cmake.preset) -DCI_BUILDID=$(GITVERSION_MAJORMINORPATCH) -DCPM_SOURCE_CACHE=$(Agent.HomeDirectory)/.cpmcache"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
          
      - task: CMake@1
        displayName: "CMake Build $(cmake.preset)"
        inputs:
          cmakeArgs: "--build --preset $(cmake.preset) -DCI_BUILDID=$(GITVERSION_MAJORMINORPATCH) -DCPM_SOURCE_CACHE=$(Agent.HomeDirectory)/.cpmcache"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
        condition: succeeded()

      - task: PublishPipelineArtifact@1
        displayName: "Publish Linux pipeline artifact $(cmake.preset)"
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/build/$(cmake.preset)"
          artifact: "build-$(cmake.preset)"
          publishLocation: "pipeline"
        condition: succeeded()
