jobs:
  - job: GitHubRelease
    displayName: GitHub Release
    pool:
      name: Default
      demands:
        - Agent.OS -equals Windows_NT
    steps:
      - checkout: none
      - task: DownloadBuildArtifacts@0
        displayName: "Download release assets"
        inputs:
          downloadType: "single"
          artifactName: "release-assets"
          downloadPath: "$(Build.ArtifactStagingDirectory)"

      - task: DownloadBuildArtifacts@0
        displayName: "Download NuGet packages"
        inputs:
          downloadType: "single"
          artifactName: "nuget-packages"
          downloadPath: "$(Build.ArtifactStagingDirectory)"
        condition: and(succeeded(), eq(variables['BuildType'], 'Release'))

      - task: NuGetCommand@2
        displayName: "NuGet push"
        inputs:
          command: "push"
          packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg"
          nuGetFeedType: "external"
          publishFeedCredentials: "sqs-nuget"
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))

      - task: GitHubRelease@1
        displayName: "Release to GitHub"
        inputs:
          gitHubConnection: "github-packages-sqs"
          repositoryName: "$(Build.Repository.Name)"
          action: "create"
          target: "$(Build.SourceVersion)"
          tagSource: "userSpecifiedTag"
          tag: "$(GITVERSION_MAJORMINORPATCH)"
          title: "v$(GITVERSION_MAJORMINORPATCH)"
          releaseNotesSource: "inline"
          releaseNotesInline: "Documentation https://github.com/$(Build.Repository.Name)"
          isPreRelease: true
          changeLogCompareToRelease: "lastFullRelease"
          changeLogType: "commitBased"
          addChangeLog: false
          assetUploadMode: "replace"
          assets: "$(Build.ArtifactStagingDirectory)/**/*"
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
