# Requirements:
# The self-hosted build agents must have CMake and Ninja installed and available in PATH for this pipeline to work.
# clang-21 or better
# gcc-16 or better
parameters:
  - name: displayName
    type: string
  - name: matrixConfigs
    type: object
  - name: runTests
    type: boolean
    default: true

jobs:
  - job: JobLinuxBuild_${{ parameters.architecture }}
    displayName: ${{ parameters.displayName }}
    workspace:
      clean: all
    pool:
      name: Default
      demands:
        - Agent.OS -equals Linux
    strategy:
      matrix: ${{ parameters.matrixConfigs }}
    steps:
      - checkout: self
        name: step1

      - task: gitversion-setup@4
        displayName: "Install GitVersion"
        inputs:
          versionSpec: "6.x"
          preferLatestVersion: true

      - task: gitversion-execute@4
        displayName: "Determine Version"
        name: version_step
        inputs:
          useConfigFile: true
          configFilePath: "GitVersion.yml"
          updateBuildNumber: true

        # Save the calculated SemVer as an Azure DevOps output variable
      - bash: echo '##vso[task.setvariable variable=TagVersion;isOutput=true]$(GITVERSION_MAJORMINORPATCH)'
        name: SetVersionForFuture
        displayName: "Set TagVersion for future stages"

      - task: CMake@1
        displayName: "CMake Configure $(cmake.preset)"
        inputs:
          cmakeArgs: "--preset $(cmake.preset) -DCI_BUILDID=$(GITVERSION_MAJORMINORPATCH) -DCPM_SOURCE_CACHE=$(Agent.HomeDirectory)/.cpmcache"
          workingDirectory: "$(System.DefaultWorkingDirectory)"

      - task: CMake@1
        displayName: "CMake Build $(cmake.preset)"
        inputs:
          cmakeArgs: "--build --preset $(cmake.preset) -DCI_BUILDID=$(GITVERSION_MAJORMINORPATCH) -DCPM_SOURCE_CACHE=$(Agent.HomeDirectory)/.cpmcache"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
        condition: succeeded()

      #- task: PublishBuildArtifacts@1
      #  displayName: "Publish Linux build artifact $(cmake.preset)"
      #  inputs:
      #    PathtoPublish: "$(System.DefaultWorkingDirectory)/build/$(cmake.preset)"
      #    ArtifactName: "build-$(cmake.preset)"
      #    publishLocation: "Container"
      #  condition: succeeded()

      - task: CMake@1
        displayName: "CMake Tests $(cmake.preset)"
        inputs:
          cmakeArgs: "-E chdir $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests ctest --output-junit $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests/results/$(cmake.preset)_test_detail.xml --output-on-failure"
        continueOnError: true
        condition: and(succeeded(), eq(${{ parameters.runTests }}, true))

      - task: PublishTestResults@2
        displayName: "Publish Test Results $(cmake.preset)_test_detail.xml"
        inputs:
          testResultsFormat: "JUnit"
          testRunTitle: "Tests $(cmake.preset)"
          testResultsFiles: "$(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests/results/$(cmake.preset)_test_detail.xml"
          mergeTestResults: false
          buildConfiguration: "$(BuildType)"
        continueOnError: true
        condition: and(succeeded(), eq(${{ parameters.runTests }}, true), or(eq(variables['BuildType'], 'Release'), failed()))
